{
 "title": "Fahrtdetails",
 "tags": [
  "timeline",
  "tripdetails"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance_id", "query": "demo" },
   { "name": "operation_day_date", "label": "Betriebstag", "query": "01.06.2026" },
   { "name": "trip_id", "label": "Fahrt-ID", "query": "de:vpe:03006_:4627" }
  ]
 },
 "panels": [
  {
   "title": "Fahrdaten",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  routes.route_name AS \"Linie\",\r\n  COALESCE(trips.concessionaire_name, routes.concessionaire_name) AS \"Konzessionär\",\r\n  COALESCE(trips.operator_name, routes.operator_name) AS \"Betreiber\"\r\nFROM\r\n  dim_trips trips\r\nINNER JOIN\r\n  dim_routes routes ON routes.route_id = trips.route_id\r\nWHERE\r\n  trips.instance_id = ANY(\r\n    STRING_TO_ARRAY(\r\n      REPLACE(REPLACE('${instance_id:raw}', '{', ''), '}', ''),\r\n      ','\r\n    )\r\n  )\r\n  AND operation_day_date = to_date('${operation_day_date}', 'DD.MM.YYYY')\r\n  AND trip_id = ${trip_id:sqlstring}"
    }
   ]
  },
  {
   "title": "Kilometer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix: km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  nom_total_distance AS \"Soll\",\r\n  act_total_distance AS \"Ist\"\r\nFROM\r\n  dim_trips\r\nWHERE\r\n  instance_id = ANY(\r\n    STRING_TO_ARRAY(\r\n      REPLACE(REPLACE('${instance_id:raw}', '{', ''), '}', ''),\r\n      ','\r\n    )\r\n  )\r\n  AND operation_day_date = to_date('${operation_day_date}', 'DD.MM.YYYY')\r\n  AND trip_id = ${trip_id:sqlstring}"
    }
   ]
  },
  {
   "title": "Fahrplanzeit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix: min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  EXTRACT(\r\n    EPOCH\r\n    FROM\r\n      (nom_end_time - nom_start_time)\r\n  ) / 60 AS \"Soll\",\r\n  EXTRACT(\r\n    EPOCH\r\n    FROM\r\n      (act_end_time - act_start_time)\r\n  ) / 60 AS \"Ist\"\r\nFROM\r\n  dim_trips\r\nWHERE\r\n  instance_id = ANY(\r\n    STRING_TO_ARRAY(\r\n      REPLACE(REPLACE('${instance_id:raw}', '{', ''), '}', ''),\r\n      ','\r\n    )\r\n  )\r\n  AND operation_day_date = to_date('${operation_day_date}', 'DD.MM.YYYY')\r\n  AND trip_id = ${trip_id:sqlstring}"
    }
   ]
  },
  {
   "title": "Pünktlichkeit Ø",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix: min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  AVG(EXTRACT(\r\n    EPOCH\r\n    FROM\r\n      (act_arrival_time - nom_arrival_time)\r\n  ) / 60) AS \"Abw. Ankunft\",\r\n  AVG(EXTRACT(\r\n    EPOCH\r\n    FROM\r\n      (act_departure_time - nom_departure_time)\r\n  ) / 60) AS \"Abw. Abfahrt\"\r\nFROM\r\n  fact_stop_times \r\nWHERE\r\n  instance_id = ANY(\r\n    STRING_TO_ARRAY(\r\n      REPLACE(REPLACE('${instance_id:raw}', '{', ''), '}', ''),\r\n      ','\r\n    )\r\n  )\r\n  AND operation_day_date = to_date('${operation_day_date}', 'DD.MM.YYYY')\r\n  AND trip_id = ${trip_id:sqlstring}\r\nGROUP BY\r\n  operation_day_date,\r\n  trip_id"
    }
   ]
  },
  {
   "title": "Haltestellen / Fahrzeiten",
   "type": "table",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  stops.stop_name AS \"Haltestelle\",\r\n  nom_arrival_time AS \"Ankunftszeit (Soll)\",\r\n  nom_departure_time AS \"Abfahrtszeit (Soll)\",\r\n  act_arrival_time AS \"Ankunftszeit (Ist)\",\r\n  act_departure_time AS \"Abfahrtszeit (Ist)\",\r\n  EXTRACT(\r\n    EPOCH\r\n    FROM\r\n      (act_arrival_time - nom_arrival_time)\r\n  ) / 60 AS \"Abw. Ankunft\",\r\n  EXTRACT(\r\n    EPOCH\r\n    FROM\r\n      (act_departure_time - nom_departure_time)\r\n  ) / 60 AS \"Abw. Abfahrt\",\r\n  distance_from_start AS \"Strecke\",\r\n  schedule_relationship AS \"Status\"\r\nFROM\r\n  fact_stop_times stop_times\r\n  INNER JOIN dim_stops stops ON stops.stop_id = stop_times.stop_id\r\nWHERE\r\n  stop_times.instance_id = ANY(\r\n    STRING_TO_ARRAY(\r\n      REPLACE(REPLACE('${instance_id:raw}', '{', ''), '}', ''),\r\n      ','\r\n    )\r\n  )\r\n  AND stop_times.operation_day_date = to_date('${operation_day_date}', 'DD.MM.YYYY')\r\n  AND stop_times.trip_id = ${trip_id:sqlstring}\r\nORDER BY\r\n  stop_sequence ASC"
    }
   ]
  },
  {
   "title": "Fahrtverlauf",
   "type": "geomap",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  stops.stop_name AS \"Haltestelle\",\r\n  stops.stop_lat AS \"Breitengrad\",\r\n  stops.stop_lon AS \"Längengrad\",\r\n  GREATEST(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (act_arrival_time - nom_arrival_time)\r\n    ) / 60,\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (act_departure_time - nom_departure_time)\r\n    ) / 60\r\n  ) AS \"Abweichung\"\r\nFROM\r\n  fact_stop_times stop_times\r\nINNER JOIN\r\n  dim_stops stops ON stops.stop_id = stop_times.stop_id\r\nWHERE\r\n  stop_times.instance_id = ANY(\r\n    STRING_TO_ARRAY(\r\n      REPLACE(REPLACE('${instance_id:raw}', '{', ''), '}', ''),\r\n      ','\r\n    )\r\n  )\r\n  AND stop_times.operation_day_date = to_date('${operation_day_date}', 'DD.MM.YYYY')\r\n  AND stop_times.trip_id = ${trip_id:sqlstring}\r\nORDER BY\r\n  stop_sequence ASC"
    }
   ]
  }
 ]
}