{
 "title": "Datenqualität",
 "tags": [
  "timeline",
  "realtime",
  "dataquality"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instanz",
    "query": "SELECT DISTINCT instance_id FROM fact_stop_times;"
   },
   {
    "name": "pipeline",
    "label": "Quelle",
    "query": "SELECT DISTINCT pipeline_id FROM fact_requests WHERE instance_id = ${instance:sqlstring};"
   },
   {
    "name": "deliverer",
    "label": "Datenlieferant",
    "query": "SELECT DISTINCT concessionaire_id FROM fact_quality_issues WHERE concessionaire_id IS NOT NULL AND instance_id = ${instance:sqlstring}\nUNION\nSELECT DISTINCT operator_id FROM fact_quality_issues WHERE operator_id IS NOT NULL AND instance_id = ${instance:sqlstring}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "### **Wichtiger Hinweis**\n\nDieses Dashboard zeigt nicht die fertig aufbereiteten Echtzeitdaten basierend auf dem Soll-Fahrplan an, sondern bezieht sich auf die eingehenden Echtzeitdaten _*nach dem Mapping*_, aber _*bevor die Daten einer Fahrt im Soll-Fahrplan*_ zugeordnet werden. Aus diesem Grund stehen in diesem Dashboard andere Filter zur Verfügung. Zweck dieses Dashboards ist die Überwachung und das Qualitätsmonitoring der Echtzeitdatenquellen. Beispielsweise können mit diesem Dashboard mögliche Gründe für das Fehlen von Echtzeitinformationen in den anderen Dashboards identifiziert werden."
   }
  },
  {
   "title": "Dateneingang",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(num_entities) AS \"Anz. Datensätze\",\r\n  SUM(age_seconds) AS \"Rückschauzeit\",\r\n  \"timestamp\" AS \"Zeitstempel\"\r\nFROM\r\n  fact_requests requests\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND requests.instance_id IN (${instance:sqlstring})\r\n  AND requests.pipeline_id IN (${pipeline:sqlstring})\r\nGROUP BY\r\n  \"timestamp\""
    }
   ]
  },
  {
   "title": "Echtzeitzuordnung",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  pipeline_id AS \"Quelle\",\r\n  ROUND(100.0 * MAX(loaded_direct_trip_count) / NULLIF(MAX(num_entities), 0), 2) AS \"DIRECT\",\r\n  ROUND(100.0 * MAX(loaded_matched_trip_count) / NULLIF(MAX(num_entities), 0), 2) AS \"MATCHING\"\r\nFROM\r\n  fact_requests requests\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND requests.instance_id IN (${instance:sqlstring})\r\n  AND requests.pipeline_id IN (${pipeline:sqlstring})\r\nGROUP BY\r\n  pipeline_id"
    }
   ]
  },
  {
   "title": "Fehlertypen",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  issue_types.code AS \"Typ\",\r\n  COALESCE(\r\n    quality_issues.operator_id,\r\n    quality_issues.concessionaire_id\r\n  ) AS \"Lieferant\",\r\n  COUNT(quality_issues.issue_id) AS \"Anzahl\"\r\nFROM\r\n  fact_quality_issues quality_issues\r\n  INNER JOIN dim_issue_types issue_types ON quality_issues.issue_type_id = issue_types.id\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND quality_issues.instance_id IN (${instance:sqlstring})\r\n  AND quality_issues.pipeline_id IN (${pipeline:sqlstring})\r\n  AND (\r\n    '${deliverer}' = ''\r\n    OR COALESCE(\r\n      quality_issues.concessionaire_id,\r\n      quality_issues.operator_id\r\n    ) = ANY(string_to_array('${deliverer}', ','))\r\n  )\r\nGROUP BY\r\n  issue_types.code,\r\n  COALESCE(\r\n    quality_issues.operator_id,\r\n    quality_issues.concessionaire_id\r\n  )"
    }
   ]
  },
  {
   "title": "Fehlerliste",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"Letzter Zeitpunkt\",\r\n  pipeline_id AS \"Quelle\",\r\n  entity_id AS \"Objekt-ID\",\r\n  issue_types.code AS \"Fehlertyp\",\r\n  assessment_value AS \"Überwachter Wert\"\r\nFROM\r\n  fact_quality_issues quality_issues\r\nINNER JOIN\r\n  dim_issue_types issue_types ON quality_issues.issue_type_id = issue_types.id\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND quality_issues.instance_id IN (${instance:sqlstring})\r\n  AND quality_issues.pipeline_id IN (${pipeline:sqlstring})\r\n  AND (\r\n    '${deliverer}' = ''\r\n    OR COALESCE(\r\n      quality_issues.concessionaire_id,\r\n      quality_issues.operator_id\r\n    ) = ANY(string_to_array('${deliverer}', ','))\r\n  )\r\nORDER BY\r\n  quality_issues.timestamp DESC"
    }
   ]
  }
 ]
}