{
 "title": "Pünktlichkeit",
 "tags": [
  "timeline",
  "performance",
  "punctuality"
 ],
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instanz",
    "query": "SELECT DISTINCT instance_id FROM fact_stop_times;"
   },
   {
    "name": "concessionaire",
    "label": "Konzessionär",
    "query": "SELECT DISTINCT concessionaire_name FROM dim_trips WHERE concessionaire_name IS NOT NULL AND instance_id = ${instance:sqlstring}\nUNION\nSELECT DISTINCT concessionaire_name FROM dim_routes WHERE concessionaire_name IS NOT NULL AND instance_id = ${instance:sqlstring}"
   },
   {
    "name": "route",
    "label": "Linie",
    "query": "SELECT DISTINCT route_name FROM dim_routes WHERE instance_id = ${instance:sqlstring} AND concessionaire_name IN (${concessionaire:sqlstring})"
   }
  ]
 },
 "panels": [
  {
   "title": "Ø Abweichung nach Haltestellen",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  stops.stop_name AS \"Haltestelle\",\r\n  AVG(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (\r\n          act_arrival_time - nom_arrival_time\r\n        )\r\n    )\r\n  ) / 60.0 AS \"Abw. Ankunft\",\r\n  AVG(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (\r\n          act_departure_time - nom_departure_time\r\n        )\r\n    )\r\n  ) / 60.0 AS \"Abw. Abfahrt\",\r\n  COUNT(DISTINCT stop_times.trip_id) AS \"Anz. Soll-Abfahrten\",\r\n  COUNT(DISTINCT stop_times.trip_id) FILTER (\r\n    WHERE\r\n      act_arrival_time IS NOT NULL\r\n      OR act_departure_time IS NOT NULL\r\n  ) AS \"Anz. Ist-Abfahrten\"\r\nFROM\r\n  fact_stop_times stop_times\r\n  INNER JOIN dim_stops stops ON stops.stop_id = stop_times.stop_id\r\n  INNER JOIN dim_trips trips ON trips.trip_id = stop_times.trip_id\r\n  INNER JOIN dim_routes routes ON routes.route_id = trips.route_id\r\nWHERE\r\n  stop_times.operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND stop_times.instance_id IN (${instance:sqlstring})\r\n  AND COALESCE(\r\n    trips.concessionaire_name,\r\n    routes.concessionaire_name\r\n  ) IN (${concessionaire:sqlstring})\r\n  AND routes.route_name IN (${route:sqlstring})\r\nGROUP BY\r\n  stops.stop_name\r\nORDER BY\r\n  stops.stop_name"
    }
   ]
  },
  {
   "title": "Ø Abweichung nach Zeitschicht",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  EXTRACT(HOUR FROM nom_arrival_time) AS \"Stunde\",\r\n  AVG(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (\r\n          act_arrival_time - nom_arrival_time\r\n        )\r\n    )\r\n  ) / 60.0 AS \"Abw. Ankunft\",\r\n  AVG(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (\r\n          act_departure_time - nom_departure_time\r\n        )\r\n    )\r\n  ) / 60.0 AS \"Abw. Abfahrt\"\r\nFROM\r\n  fact_stop_times stop_times\r\n  INNER JOIN dim_trips trips ON trips.trip_id = stop_times.trip_id\r\n  INNER JOIN dim_routes routes ON routes.route_id = trips.route_id\r\nWHERE\r\n  stop_times.operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND stop_times.instance_id IN (${instance:sqlstring})\r\n  AND COALESCE(\r\n    trips.concessionaire_name,\r\n    routes.concessionaire_name\r\n  ) IN (${concessionaire:sqlstring})\r\n  AND routes.route_name IN (${route:sqlstring})\r\nGROUP BY\r\n  EXTRACT(HOUR FROM nom_arrival_time)\r\nORDER BY \r\n  EXTRACT(HOUR FROM nom_arrival_time)\r\n"
    }
   ]
  },
  {
   "title": "Pünktlichkeit im Verlauf",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  trips.operation_day_date AS \"Datum\",\r\n  AVG(\r\n    GREATEST(\r\n      0,\r\n      100.0 - ABS(\r\n        (\r\n          (\r\n            EXTRACT(\r\n              EPOCH\r\n              FROM\r\n                (\r\n                  act_end_time - act_start_time\r\n                )\r\n            ) - EXTRACT(\r\n              EPOCH\r\n              FROM\r\n                (\r\n                  nom_end_time - nom_start_time\r\n                )\r\n            )\r\n          ) / NULLIF(\r\n            EXTRACT(\r\n              EPOCH\r\n              FROM\r\n                (\r\n                  nom_end_time - nom_start_time\r\n                )\r\n            ),\r\n            0\r\n          )\r\n        ) * 100.0\r\n      )\r\n    )\r\n  ) AS \"Pünktlichkeit\"\r\nFROM\r\n  dim_trips trips\r\n  INNER JOIN dim_routes routes ON routes.route_id = trips.route_id\r\nWHERE\r\n  trips.instance_id IN (${instance:sqlstring})\r\n  AND COALESCE(\r\n    trips.concessionaire_name,\r\n    routes.concessionaire_name\r\n  ) IN (${concessionaire:sqlstring})\r\n  AND routes.route_name IN (${route:sqlstring})\r\n  AND act_start_time IS NOT NULL\r\n  AND act_end_time IS NOT NULL\r\nGROUP BY\r\n  trips.operation_day_date\r\nORDER BY\r\n  trips.operation_day_date;"
    }
   ]
  }
 ]
}