{
 "title": "Erfüllungsgrad",
 "tags": [
  "timeline",
  "performance",
  "fulfillment"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instanz",
    "query": "SELECT DISTINCT instance_id FROM fact_stop_times;"
   },
   {
    "name": "concessionaire",
    "label": "Konzessionär",
    "query": "SELECT DISTINCT concessionaire_name FROM dim_trips WHERE concessionaire_name IS NOT NULL AND instance_id = ${instance:sqlstring}\nUNION\nSELECT DISTINCT concessionaire_name FROM dim_routes WHERE concessionaire_name IS NOT NULL AND instance_id = ${instance:sqlstring}"
   },
   {
    "name": "route",
    "label": "Linie",
    "query": "SELECT route_name FROM dim_routes WHERE instance_id = ${instance:sqlstring} AND concessionaire_name IN (${concessionaire:sqlstring})"
   },
   { "name": "act_values_mode", "label": "Ist-Werte", "query": "Verifiziert : 0, Gesamt : 1" }
  ]
 },
 "panels": [
  {
   "title": "Kilometer",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix: km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(nom_total_distance) AS \"Soll\",\r\n  SUM(\r\n    CASE\r\n      WHEN schedule_relationship = 'SCHEDULED' THEN act_total_distance\r\n      WHEN ${act_values_mode} = 1\r\n      AND schedule_relationship = 'UNKNOWN' THEN nom_total_distance\r\n      ELSE 0\r\n    END\r\n  ) AS \"Ist\",\r\n  SUM(nom_total_distance) FILTER (\r\n    WHERE\r\n      trips.schedule_relationship IN ('CANCELLED')\r\n  ) AS \"Ausfall\"\r\nFROM\r\n  dim_trips trips\r\n  INNER JOIN dim_routes routes ON routes.route_id = trips.route_id\r\nWHERE\r\n  trips.operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND trips.instance_id IN (${instance:sqlstring})\r\n  AND COALESCE(\r\n    trips.concessionaire_name,\r\n    routes.concessionaire_name\r\n  ) IN (${concessionaire:sqlstring})\r\n  AND routes.route_name IN (${route:sqlstring})"
    }
   ]
  },
  {
   "title": "Erfüllungsgrad Kilometer nach Linie",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  routes.route_name AS \"Linie\",\r\n  SUM(nom_total_distance) AS \"Soll\",\r\n  SUM(\r\n    CASE\r\n      WHEN schedule_relationship = 'SCHEDULED' THEN act_total_distance\r\n      WHEN ${act_values_mode} = 1\r\n      AND schedule_relationship = 'UNKNOWN' THEN nom_total_distance\r\n      ELSE 0\r\n    END\r\n  ) AS \"Ist\",\r\n  SUM(nom_total_distance) FILTER (\r\n    WHERE\r\n      trips.schedule_relationship IN ('CANCELLED')\r\n  ) AS \"Ausfall\"\r\nFROM\r\n  dim_trips trips\r\n  INNER JOIN dim_routes routes ON routes.route_id = trips.route_id\r\nWHERE\r\n  trips.operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND trips.instance_id IN (${instance:sqlstring})\r\n  AND COALESCE(\r\n    trips.concessionaire_name,\r\n    routes.concessionaire_name\r\n  ) IN (${concessionaire:sqlstring})\r\n  AND routes.route_name IN (${route:sqlstring})\r\nGROUP BY\r\n  routes.route_name\r\nORDER BY\r\n  regexp_replace(route_name, '\\d', '', 'g'),\r\n  NULLIF(\r\n    regexp_replace(route_name, '\\D', '', 'g'),\r\n    ''\r\n  ) :: INT;"
    }
   ]
  },
  {
   "title": "Fahrplanstunden",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix: h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (nom_end_time - nom_start_time)\r\n    ) / 3600\r\n  ) AS \"Soll\",\r\n  SUM(\r\n    CASE\r\n      WHEN schedule_relationship = 'SCHEDULED' THEN \r\n      EXTRACT(\r\n        EPOCH\r\n        FROM\r\n          (act_end_time - act_start_time)\r\n      ) / 3600\r\n      WHEN ${act_values_mode} = 1\r\n      AND schedule_relationship = 'UNKNOWN' THEN \r\n      EXTRACT(\r\n        EPOCH\r\n        FROM\r\n          (nom_end_time - nom_start_time)\r\n      ) / 3600\r\n      ELSE 0\r\n    END\r\n  ) AS \"Ist\",\r\n  SUM(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (nom_end_time - nom_start_time)\r\n    ) / 3600) FILTER (\r\n    WHERE\r\n      trips.schedule_relationship IN ('CANCELLED')\r\n  ) AS \"Ausfall\"\r\nFROM\r\n  dim_trips trips\r\n  INNER JOIN dim_routes routes ON routes.route_id = trips.route_id\r\nWHERE\r\n  trips.operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND trips.instance_id IN (${instance:sqlstring})\r\n  AND COALESCE(\r\n    trips.concessionaire_name,\r\n    routes.concessionaire_name\r\n  ) IN (${concessionaire:sqlstring})\r\n  AND routes.route_name IN (${route:sqlstring})"
    }
   ]
  },
  {
   "title": "Erfüllungsgrad Fahrplanstunden nach Linie",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  routes.route_name AS \"Linie\",\r\n  SUM(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (nom_end_time - nom_start_time)\r\n    ) / 3600\r\n  ) AS \"Soll\",\r\n  SUM(\r\n    CASE\r\n      WHEN schedule_relationship = 'SCHEDULED' THEN \r\n      EXTRACT(\r\n        EPOCH\r\n        FROM\r\n          (act_end_time - act_start_time)\r\n      ) / 3600\r\n      WHEN ${act_values_mode} = 1\r\n      AND schedule_relationship = 'UNKNOWN' THEN \r\n      EXTRACT(\r\n        EPOCH\r\n        FROM\r\n          (nom_end_time - nom_start_time)\r\n      ) / 3600\r\n      ELSE 0\r\n    END\r\n  ) AS \"Ist\",\r\n  SUM(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (nom_end_time - nom_start_time)\r\n    ) / 3600) FILTER (\r\n    WHERE\r\n      trips.schedule_relationship IN ('CANCELLED')\r\n  ) AS \"Ausfall\"\r\nFROM\r\n  dim_trips trips\r\n  INNER JOIN dim_routes routes ON routes.route_id = trips.route_id\r\nWHERE\r\n  trips.operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND trips.instance_id IN (${instance:sqlstring})\r\n  AND COALESCE(\r\n    trips.concessionaire_name,\r\n    routes.concessionaire_name\r\n  ) IN (${concessionaire:sqlstring})\r\n  AND routes.route_name IN (${route:sqlstring})\r\nGROUP BY\r\n  routes.route_name\r\nORDER BY\r\n  regexp_replace(route_name, '\\d', '', 'g'),\r\n  NULLIF(\r\n    regexp_replace(route_name, '\\D', '', 'g'),\r\n    ''\r\n  ) :: INT;"
    }
   ]
  }
 ]
}