{
 "title": "Übersicht",
 "tags": [
  "overview",
  "timeline"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instanz",
    "query": "SELECT DISTINCT instance_id FROM fact_stop_times"
   }
  ]
 },
 "panels": [
  {
   "title": "Pünktlichkeit Ø",
   "type": "geomap",
   "gridPos": { "h": 29, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  stop_name AS Name,\r\n  stop_lat AS Breitengrad,\r\n  stop_lon AS Längengrad\r\nFROM\r\n  dim_stops\r\nWHERE\r\n  instance_id IN (${instance:sqlstring})\r\n  AND stop_lat <> 0.0\r\n  AND stop_lon <> 0.0"
    },
    {
     "rawSql": "SELECT\r\n  stops.stop_lat,\r\n  stops.stop_lon,\r\n  AVG(\r\n    GREATEST(\r\n      EXTRACT(\r\n        EPOCH\r\n        FROM\r\n          (act_arrival_time - nom_arrival_time)\r\n      ) / 60,\r\n      EXTRACT(\r\n        EPOCH\r\n        FROM\r\n          (act_departure_time - nom_departure_time)\r\n      ) / 60\r\n    )\r\n  ) AS Verspätung\r\nFROM\r\n  fact_stop_times stop_times\r\n  INNER JOIN dim_stops stops ON stop_times.stop_id = stops.stop_id\r\n  INNER JOIN dim_trips trips ON stop_times.trip_id = trips.trip_id\r\nWHERE\r\n  stop_times.operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND stop_times.instance_id IN (${instance:sqlstring})\r\n  AND stop_times.act_arrival_time IS NOT NULL\r\n  AND stops.stop_lat <> 0.0\r\n  AND stops.stop_lon <> 0.0\r\nGROUP BY\r\n  stops.stop_lat,\r\n  stops.stop_lon,\r\n  stop_times.stop_id"
    }
   ]
  },
  {
   "title": "Gefahrene Kilometer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix: km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(act_total_distance) AS GefahreneKilometer\r\nFROM\r\n  dim_trips\r\nWHERE\r\n  operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND instance_id = ${instance:sqlstring}\r\n  AND schedule_relationship <> 'UNKNOWN'\r\n  AND schedule_relationship <> 'CANCELLED'"
    }
   ]
  },
  {
   "title": "Gefahrene Fahrplanzeit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "suffix:h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(\r\n    EXTRACT(\r\n      EPOCH\r\n      FROM\r\n        (act_end_time - act_start_time)\r\n    ) / 3600\r\n  ) AS GefahreneFahrplanzeit\r\nFROM\r\n  dim_trips\r\nWHERE\r\n  operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND instance_id = ${instance:sqlstring}\r\n  AND schedule_relationship <> 'UNKNOWN'\r\n  AND schedule_relationship <> 'CANCELLED'"
    }
   ]
  },
  {
   "title": "Anzahl Fahrtausfälle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(*) AS AnzahlFahrtausfälle\r\nFROM\r\n  dim_trips\r\nWHERE\r\n  operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND schedule_relationship = 'CANCELLED'"
    }
   ]
  },
  {
   "title": "Echtzeitquote",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(\r\n    (\r\n      COUNT(*) FILTER (\r\n        WHERE\r\n          schedule_relationship <> 'UNKNOWN'\r\n      ) :: NUMERIC / COUNT(*) :: NUMERIC\r\n    ) * 100,\r\n    2\r\n  ) AS \"Echtzeitquote\"\r\nFROM\r\n  dim_trips\r\nWHERE\r\n  operation_day_date BETWEEN '${__from:date:YYYY-MM-DD}' :: DATE\r\n  AND '${__to:date:YYYY-MM-DD}' :: DATE\r\n  AND instance_id = ${instance:sqlstring}"
    }
   ]
  }
 ]
}